#!/bin/bash

# WARNING: Run this script from seduce_pp directory
# PiMaster Configuration
INTERFACE="IFACE_CONF"
MASTER_PORT="MASTER_PORT_CONF"
GATEWAY_IP="GATEWAY_IP_CONF"
# Switch Configuration
SWITCH_IP="SWITCH_IP_CONF"
NB_PORT="NB_PORT_CONF"
# SNMP Configuration
SNMP_COMMUNITY="SNMP_COMMUNITY_NAME"
SNMP_OID="SNMP_OID_CONF"
SNMP_OID_OFFSET="SNMP_OID_CONF_OFFSET"
ON="1"
OFF="2"
# Slave configuration
NETWORK_IP="NETWORK_IP_CONF"
INC_IP="INC_IP_CONF"
# Database configuration
DB_ROOT_PWD="CHANGE_ME_ROOT"
DB_USER_PWD="CHANGE_ME_USER"
# Restrict the switch ports to use. Default value should be "", otherwise use port numbers, e.g., "1 6 12"
PORTS=""

if [ -z "$PORTS" ]; then
    PORTS=$(seq 1 $NB_PORT)
fi

# Remove the PiMaster port
PORTS=$(echo $PORTS | sed "s/$MASTER_PORT //")

MY_GATEWAY=$(route -n | grep -A 1 Gateway | tail -n 1 | awk '{ print $2 }')
if [ $MY_GATEWAY != $GATEWAY_IP ]; then
    echo "# Configure the network gateway"
    sed -i "s/routers=.*/routers=$GATEWAY_IP/" /etc/dhcpcd.conf
    sed -i "s/domain_name_servers=.*/domain_name_servers=$GATEWAY_IP/" /etc/dhcpcd.conf
    dhcpcd -n $INTERFACE
    sleep 10
fi

echo "# Create the dnsmasq configuration"
MASTER_IP=$(ifconfig | grep -A 1 eth0 | grep inet | awk '{ print $2}')
echo " +  Add my IP '$MASTER_IP' to the dnsmasq configuration"
cp autoconf/files/dnsmasq.conf dnsmasq.conf
sed -i "s/PIMASTERIP/$MASTER_IP/" dnsmasq.conf
echo "dhcp-range=$NETWORK_IP.0,static,255.255.255.0" >> dnsmasq.conf

echo "# Register the pimaster (me) to the cluster configuration"
cp autoconf/files/main.json .
sed -i "s/PIMASTERIP/$MASTER_IP/" main.json
sed -i "s/SWITCHIP/$SWITCH_IP/" main.json
sed -i "s/SNMPCOMMUNITY/$SNMP_COMMUNITY/" main.json
sed -i "s/SNMPOID/$SNMP_OID/" main.json
sed -i "s/SNMPOIDOFFSET/$SNMP_OID_OFFSET/" main.json
mv main.json cluster_desc

echo '# Configure the seduce_pp database access'
sed -i "s/DBPASSWORD/$DB_USER_PWD/" seducepp.conf

mysql -e "SHOW DATABASES" &> /dev/null
if [ $? -eq 0 ]; then
    echo '# Configure the mysql server'
    # Make sure that NOBODY can access the server without a password
    mysql -e "UPDATE mysql.user SET Password = PASSWORD('$DB_ROOT_PWD') WHERE User = 'root'"
    # Delete anonymous users
    mysql -e "DELETE FROM mysql.user WHERE User='';"
    # Ensure the root user can not log in remotely
    mysql -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
    # Kill off the demo database
    mysql -e "DROP DATABASE test"
    mysql -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
    # Create the database
    mysql -e "CREATE DATABASE piseduce"
    # Create the user 'pipi'
    mysql -e "CREATE USER 'pipi'@'localhost' IDENTIFIED BY '$DB_USER_PWD'"
    # Grant access to the database
    mysql -e "GRANT USAGE ON *.* TO 'pipi'@localhost IDENTIFIED BY '$DB_USER_PWD';"
    mysql -e "GRANT USAGE ON *.* TO 'pipi'@'%' IDENTIFIED BY '$DB_USER_PWD';"
    mysql -e "GRANT ALL PRIVILEGES ON piseduce.* TO 'pipi'@'localhost';"
    # Make our changes take effect
    mysql -e "FLUSH PRIVILEGES"
fi

echo "# Configure SSH access to the nodes"
echo "Host $NETWORK_IP.*" > /root/.ssh/config
echo "    StrictHostKeyChecking no" >> /root/.ssh/config
echo "" >> /root/.ssh/config
echo "Host node*.local" >> /root/.ssh/config
echo "    StrictHostKeyChecking no" >> /root/.ssh/config

echo "# Configuring the DHCP server"
echo "# Turn off all nodes connected to $SWITCH_IP"
for p in $PORTS; do
    retry="again"
    while [ ! -z "$retry" ]; do
        snmpset -v2c -c $SNMP_COMMUNITY $SWITCH_IP $SNMP_OID.$(( $p + $SNMP_OID_OFFSET)) i $OFF
        if [ $? -eq 0 ]; then
            retry=""
        fi
    done
done

sleep 1
echo "# Detecting MAC addresses"
success_ip_list=""
for p in $PORTS; do
    echo " + Turn on the node on port $p"
    snmpset -v2c -c $SNMP_COMMUNITY $SWITCH_IP $SNMP_OID.$(( $p + $SNMP_OID_OFFSET)) i $ON
    sleep 5
    echo " + Capturing PXE boot requests"
    tshark -nni eth0 -w port.pcap -a duration:10 port 67 and 68
    echo " + Analyzing captured requests"
    mac=$(tshark -r port.pcap -Y "bootp.option.type == 53 and bootp.ip.client == 0.0.0.0"\
        -T fields -e frame.time -e bootp.ip.client -e bootp.hw.mac_addr |\
        awk '{ print $7 }' | uniq)
    echo "Detected MAC address: $mac"
    if [ $(echo $mac | wc -c) -gt 16 ]; then
        echo "  - MAC node on port $p: $mac"
        node_ip=$NETWORK_IP.$(( $p + $INC_IP))
        echo "  - Associated the MAC address to $node_ip"
        echo "dhcp-host=$mac,node-$p,$node_ip" >> dnsmasq.conf
        echo " - Configure the mDNS hostname for 'node-$p'"
        echo "$node_ip node-$p.local" >> /etc/avahi/hosts
        success_ip_list="$success_ip_list $node_ip"
    else
        echo "  - Failed to retrieve the MAC address for the node on port $p"
    fi
    echo " + Turn off the node on port $p"
    snmpset -v2c -c $SNMP_COMMUNITY $SWITCH_IP $SNMP_OID.$(( $p + $SNMP_OID_OFFSET)) i $OFF
done
rm -f port.pcap

echo "# Move the configuration file to /etc"
mv dnsmasq.conf /etc/

echo "# Node first boot"
echo " + Start services"
service dnsmasq restart
service nfs-kernel-server restart
echo " + Prepare tftpboot files"
cp autoconf/files/cmdline.txt /tftpboot/rpiboot_uboot/
sed -i "s/PIMASTERIP/$MASTER_IP/" /tftpboot/rpiboot_uboot/cmdline.txt
cp -r /tftpboot/rpiboot_uboot/* /tftpboot/
echo " + Turn on all nodes"
for p in $PORTS; do
    echo "  - Turn on the node on port $p"
    snmpset -v2c -c $SNMP_COMMUNITY $SWITCH_IP $SNMP_OID.$(( $p + $SNMP_OID_OFFSET)) i $ON
done
echo " + Waiting 45s for the nodes"
sleep 45
for p in $PORTS; do
    echo " + SSH connection to 'node-$p'"
    node_ip=$NETWORK_IP.$(( $p + $INC_IP))
    if [[ $success_ip_list == *"$node_ip"* ]]; then
        SSH_OK=""
        while [ -z "$SSH_OK" ]; do
            ssh -o StrictHostKeyChecking=no $node_ip 'echo ""'
            if [ $? -eq 0 ]; then
                echo "  - SSH: OK"
                SSH_OK="yes"
            else
                echo "  - SSH connection failed to '$node_ip'"
            fi
            sleep 5
        done
        echo " + Get the node identifier"
        node_id=$(ssh -o StrictHostKeyChecking=no $node_ip "cat /proc/cpuinfo" | \
            grep "Serial" | awk '{ print substr( $3, length($3) - 7, length($3) ) }')
        echo " + Create the cluster configuration associated to 'node-$p'"
        node_file="cluster_desc/nodes/node-$p.json"
        if [ $p -lt 10 ]; then
            json_file="autoconf/files/node-default.json"
        else
            json_file="autoconf/files/node-default10.json"
        fi
        cp $json_file $node_file
        sed -i "s/NODENAME/node-$p/" $node_file
        sed -i "s/NODEPORT/$p/" $node_file
        sed -i "s/NODEIP/$node_ip/" $node_file
        node_file="cluster_desc/nodes/node-$p.json"
        sed -i "s/NODEID/$node_id/" $node_file
    else
        echo "Node IP '$node_ip' is not configured"
    fi
done
echo " + Turn off all nodes"
for p in $PORTS; do
    echo "  - Turn off the node on port $p"
    snmpset -v2c -c $SNMP_COMMUNITY $SWITCH_IP $SNMP_OID.$(( $p + $SNMP_OID_OFFSET)) i $OFF
done
echo " + Clean the tftpboot directory"
for f in $(ls /tftpboot/rpiboot_uboot); do
    rm -rf /tftpboot/$f
done

service pitasks restart
sleep 10
echo "# Connect to http://pimaster.local:9000/"
echo "# login: 'admin@piseduce.fr', password: 'piseduceadmin'"
service pifrontend restart
systemctl enable dnsmasq
systemctl enable nfs-kernel-server
systemctl enable pitasks
